version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_NAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - 'default-network'
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${SERVER_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: '${DB_HOST}:${DB_PORT}'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DEBUG: 1
    volumes: 
      - .:/var/www/html/wp-content
    networks:
      - 'default-network'
networks:
  default-network:
    driver: bridge
volumes:
  db_data: